---
- name: PLAY 1
  hosts: ACI
  any_errors_fatal: true
  connection: local
  gather_facts: no
  vars:
    aci_host: sandboxapicdc.cisco.com
    aci_username: admin
    aci_password: ciscopsdt
    # Tenant Vars
    Tenant_Name: 000_dsp_2020
    Tenant_Description: Tenant created by Ansible via role.
    # VRF Vars
    VRF_Name: VRF-Prod
    VRF_Description: VRF created by Ansible via role.
    # Filter Vars
    Filter_Name: Filter1
    Filter_Description: Filter1 Description
    # Filter Entry Vars
    FilterEntry_Name: FLTe_SNMP
    FilterEntry_Description: UDP Port 161 for SNMP
    FilterEntry_Ethertype: ip
    FilterEntry_Protocol: udp
    FilterEntry_DSTPort: "161"
    # Application Profile Vars
    ApplicationProfile_Name: app1
    ApplicationProfile_Description: app1 desc
    #Bridge Domain Vars
    BridgeDomain_Name: brige1
    # EPG Vars
    EPG_Name: epg1
    EPG_Description: epg1 desc
    # Subnet Vars
    Subnet_Name: sub1
    Subnet_Description: sub1 desc
    Subnet_Scope: public
    Subnet_Gateway: 10.0.0.254
    Subnet_Netmask: 24
  roles:
      - CreateTenant
      - CreateVRF
      - CreateFilter
      - CreateFilterEntry
      - CreateBridgeDomain
      - CreateSubnet
      - CreateApplicationProfile
      - CreateEPG


