---
- name: PLAY 1
  hosts: ACI
  # any_errors_fatal: true
  connection: local
  gather_facts: no
  vars:
    aci_host: sandboxapicdc.cisco.com
    aci_username: admin
    aci_password: ciscopsdt
    # Filter Entry Vars
    FilterEntry_Name: FLTe-SNMP2
    FilterEntry_Description: UDP Port for SNMP
    FilterEntry_Ethertype: ip
    FilterEntry_Protocol: udp
    FilterEntry_DSTPort_Start: 210
    #FilterEntry_DSTPort_End: 250
    Tenant_Name: 000_dsp_2021
    Filter_Name: FLT-Monitoring

  tasks:
    - name: Create Filter Entry "{{ FilterEntry_Name }}"
      aci_filter_entry:
        host: "{{ aci_host }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        state: present
        ip_protocol: "{{ FilterEntry_Protocol }}"
        entry: "{{ FilterEntry_Name }}"
        ether_type: "{{ FilterEntry_Ethertype }}"
        tenant: "{{ Tenant_Name }}"
        dst_port_start: "{{ FilterEntry_DSTPort_Start }}"
        dst_port_end: "{{ FilterEntry_DSTPort_End }}"
        filter: "{{ Filter_Name }}"
        descr: "{{ FilterEntry_Description }}"
      when: FilterEntry_DSTPort_End is defined

    - name: Create Single Port Filter Entry "{{ FilterEntry_Name }}"
      aci_filter_entry:
        host: "{{ aci_host }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        state: present
        ip_protocol: "{{ FilterEntry_Protocol }}"
        entry: "{{ FilterEntry_Name }}"
        ether_type: "{{ FilterEntry_Ethertype }}"
        tenant: "{{ Tenant_Name }}"
        dst_port: "{{ FilterEntry_DSTPort_Start }}"
        filter: "{{ Filter_Name }}"
        descr: "{{ FilterEntry_Description }}"
      when: FilterEntry_DSTPort_End is undefined
    