---
- name: Query Filter Entry "{{ FilterEntry_Name }}"
  aci_filter_entry:
    host: "{{ aci_host }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: no
    state: query
    entry: "{{ FilterEntry_Name }}"
  register: my_FilterEntry

- name: Create Filter Entry "{{ FilterEntry_Name }}"
  aci_filter_entry:
    host: "{{ aci_host }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: no
    state: present
    ip_protocol: "{{ FilterEntry_Protocol }}"
    entry: "{{ FilterEntry_Name }}"
    ether_type: "{{ FilterEntry_Ethertype }}"
    tenant: "{{ Tenant_Name }}"
    dst_port: "{{ FilterEntry_DSTPort }}"
    filter: "{{ Filter_Name }}"
    descr: "{{ FilterEntry_Description }}"
  when: my_FilterEntry.current == []