- name: Query Tenant 
  aci_tenant:
    host: "{{ aci_host }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: no
    tenant: "{{ Tenant_Name }}"
    description: "{{ Tenant_Description }}"
    state: query
  register: my_tenant
- name: Create tenant "{{ Tenant_Name }}"
  aci_tenant:
    host: "{{ aci_host }}"
    username: "{{ aci_username }}"
    password: "{{ aci_password }}"
    validate_certs: no
    tenant: "{{ Tenant_Name }}"
    description: "{{ Tenant_Description }}"
    state: present
  when: my_tenant.current == []